### ISSUE TITLE
Update packages to latest and align on NodeJS v18 and v20 and add missing ones

### ISSUE THREAD

**Issue by bokjo** [vuestorefront/integration-boilerplate#21]
### Describe the feature

Some packages in the boilerplate are hardcoded to an exact version that should be the case!

- `@vue-storefront/middleware` => https://github.com/vuestorefront/integration-boilerplate/blob/main/playground/middleware/package.json#L12
- `@vue-storefront/sdk` => https://github.com/vuestorefront/integration-boilerplate/blob/main/packages/sdk/package.json#L27
- "@vue-storefront/middleware": "3.0.0-rc.2" => https://github.com/vuestorefront/integration-boilerplate/blob/main/packages/api-client/package.json#L20
- import from "@vue-storefront/middleware" in the test setup but the package is not provided in package.json as devDeps, test is failing! => https://github.com/vuestorefront/integration-boilerplate/blob/main/packages/sdk/__tests__/integration/__config__/jest.setup.global.ts#L1

Is there a specific reason to run rollup v2?
Updating all packages to the latest and running them against NodeJS v20

fails due to `import { terser } from 'rollup-plugin-terser';` package... suggestion: updating to package `import terser from '@rollup/plugin-terser';` solves the issue

update to rollup from v2 to v3: (to make it work)
- update all packages
- https://github.com/vuestorefront/integration-boilerplate/blob/main/rollup.base.config.js#L1 `import  nodeResolve from '@rollup/plugin-node-resolve';` becomes => `import { nodeResolve } from '@rollup/plugin-node-resolve';` (due to CJS - ESM module resolution error)
- add `--bundleConfigAsCjs` to all the npm scripts that use rollup
  - https://github.com/vuestorefront/integration-boilerplate/blob/main/packages/api-client/package.json#L14
  - https://github.com/vuestorefront/integration-boilerplate/blob/main/packages/api-client/package.json#L15
  - https://github.com/vuestorefront/integration-boilerplate/blob/main/packages/sdk/package.json#L11
  - https://github.com/vuestorefront/integration-boilerplate/blob/main/packages/sdk/package.json#L12

Lerna:
After update to the latest version the `useWorkspaces` config is not needed (inferred from package.json which already has the workspaces setup done!) => https://github.com/vuestorefront/integration-boilerplate/blob/main/lerna.json#L2C4-L2C17

Missing stuff:
Add NCU and check and update package scripts 
```json
"update:check": "ncu && lerna run update:check --stream",
 "update:update": "ncu -u && lerna run update:update --stream"
```

Extra not needed deps?
What is the need for `react` and `react-dom` to be part of this boilerplate? https://github.com/vuestorefront/integration-boilerplate/blob/main/package.json#L47

Missing stuff from this boilerplate but that is added to the `playground/app` presume with a different template
- `playground/app/sdk.config.ts` imports `import { initSDK, buildModule } from '@vue-storefront/sdk';` but the `@vue-storefront/sdk` package is not part of the package.json dependencies! (p.s don't know why it works with yarn tho, but not with npm)

Docs setup assumes you have `yarn` installed as it is hardcoded in the scripts, please change this one if you have already chosen to use `npm` as the package manager!
ref: https://github.com/vuestorefront/integration-boilerplate/blob/main/docs/package.json#L10

`.husly` is present in the boilerplate but `husky` package is not installed and `prepare` husky install script is missing

`Prettier` and `ESLint`  present in the boilerplate repo but not installed (removed) when generating the integration?

p.s I might have missed something!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://github.com/vuestorefront/.github/blob/main/CONTRIBUTING.md).
- [X] Check existing discussions and issues.

**Comment by bokjo** [comment]
Here for vizibility instead of editing the main one!

```sh
npm ERR! code EWORKSPACESCONFIG
npm ERR! workspaces config expects an Array

npm ERR! A complete log of this run can be found in: /Users/bojanche/.npm/_logs/2023-09-29T13_31_43_414Z-debug-0.log
[1]    92542 exit 1     npm i
```

when building the docs with `npm`... node idea for `yarn`

removing it helps!

issue when running `npm run api-extract` and `npm run dev` for the first time... need to run `npx browserslist@latest --update-db` first! afterwards is fine.


Fails on `npm run build` tho...
```sh
npm run build

> @propeller-commerce/storefront-docs@0.0.1 build
> NODE_OPTIONS=--max_old_space_size=8192 vuepress build

wait Extracting site metadata...
tip Apply theme vuepress-theme-vsf-docs ...
warning An error was encountered in plugin "@vuepress/medium-zoom"
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin vuepress-plugin-anonymous-5d1d00eb ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...

✖ Client
  Compiled with some errors in 4.57s

✔ Server
  Compiled successfully in 3.89s

(undefined) assets/js/styles.a3a5a341.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/app.f66d3ddf.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/2.3bb616eb.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/3.be4716df.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/4.b82d605e.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/5.26dae86f.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/6.6bbd2223.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/7.c3f540ba.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/8.07395eeb.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/9.1a7aa679.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/10.d6548717.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/11.5b5b30a4.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/12.6531c872.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/13.574fe82e.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/14.027d71dd.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/15.5779bad2.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/16.1abf40b0.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/17.5e49bca6.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/18.76bd38a9.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/19.ce771dda.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/20.466a6ca3.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/21.0f2f31e2.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/22.4f059c5a.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
(undefined) assets/js/23.9c52f942.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:160:259)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
Error: Failed to compile with errors.
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/@vuepress/core/lib/node/build/index.js:190:16
    at finalCallback (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/MultiCompiler.js:254:12)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/MultiCompiler.js:277:6
    at done (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/neo-async/async.js:2931:13)
    at runCompilers (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/MultiCompiler.js:181:48)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/MultiCompiler.js:188:7
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/MultiCompiler.js:270:7
    at finalCallback (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/Compiler.js:273:13
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/Compiler.js:271:21)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at /Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:321:9
    at TaskRunner.run (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/TaskRunner.js:48:7)
    at TerserPlugin.optimizeFn (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/terser-webpack-plugin/dist/index.js:227:18)
    at _next0 (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at eval (eval at create (/Users/bojanche/dev/frontend/storefront-sdk/docs/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
[1]    92635 exit 1     npm run build
``` 

will have to check what the deal with `terser-webpack-plugin` and `webpack` is... maybe will just try to upgrade packages to latest and call it a day!
